### ISSUE TITLE
Expand config docs

### ISSUE THREAD

**Issue by jefftriplett** [simonw/datasette-ripgrep#15]
Feel free to close this, but I struggled to figure out how to configure this plugin, what the config file should be called, and where it should live. 

I skimmed docs and started with config.json, but I keep seeing `The path plugin configuration is required.` 

Eventually, I noticed `datasette serve --metadata=metadata.json` in some examples from your main docs. (I'll submit a patch for a typo I noticed too.)

I'm opening this for anyone else who tries it out and runs into this issue.

**Comment by simonw** [comment]
Yeah, this is a wider problem with Datasette: `metadata.json` started out as a feature for adding license/source metadata, but it grew all kinds of extra features related to configuration, especially for plugins.

I have an open issue for fixing that here: https://github.com/simonw/datasette/issues/493 - it's included in the 1.0 milestone, but it's going to take a fair bit of work to redesign everything.

In the meantime, expanding the  documentation for this plugin feels like a good idea.
