### ISSUE TITLE
Use -e to avoid input being treated as a command-line switch

### ISSUE THREAD

**Issue by gijsh** [simonw/datasette-ripgrep#7]
I noticed that when you search for something that is a command line argument to ripgrep this will get interpreted.

For example searching for '-v' will cause ripgrep to interpret the -v as a command line switch and return the non matching lines instead of searching for the string -v.

Solution might be as easy as adding '-e' option before the search term in run_ripgrep to tell ripgrep to interpret the next argument as a pattern.

**Comment by simonw** [comment]
Oops! That's bad. Thanks for the `-e` suggestion.
